### ISSUE TITLE
'installutil' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by timabell** [jcdickinson/tfsslackbot#6]
Following the instructions in the readme I got this:

    'installutil' is not recognized as an internal or external command,
    operable program or batch file.

Windows 10. VS 2015.

**Comment by timabell** [comment]
You have to use a "developer command prompt", which has the right path. I suggest updating the readme.

**Comment by shaikmdrafi24** [comment]
I am trying to install a windows service but not able to install...

<img width="863" alt="error" src="https://user-images.githubusercontent.com/25167783/29763824-5b102a4e-8bf2-11e7-83f5-96deab52c0cc.png">

can anyone help me to resolve...
